### ISSUE TITLE
[Bug] Radio-Buttons + Checkbox Laden keinen Wert

### ISSUE THREAD

**Issue by mathe42** [ecnordbund/ec-verwaltungs-app#102]
Radio-Buttons + Checkbox Laden keinen Wert laden in ec-form components keinen Init-Wert wieso???

**Comment by mathe42** [comment]
Wähle eine Person aus und editiere die Stammdaten. Welches Geschlecht ist gewählt?...

**Comment by tobikrs** [comment]
Habe es für Personen fixen können (s. 9515000d3cbba55ce5023a422cfe83d3a8338484)... Taucht es noch wo anders auf?

**Comment by mathe42** [comment]
Ja. Im gesamten lib_extension/radiobuttons ordner und bei lib_extension/selects (das sollte aber in der lib/formElements/selects/select.ts gefixt werden) und bei der Checkbox lib/formElements/inputs/checkbox.vue

**Comment by tobikrs** [comment]
`lib/formElements/selects/select.ts` at `line 28` hat schon die `value`-Prop

**Comment by tobikrs** [comment]
Müsste durch #118 alles gefixt sein, oder?

**Comment by mathe42** [comment]
Ist nicht alles gefixt aber das was aus dem Grund den du gefunden hast nicht ging ist gefixt das andere ist wohl komplexer...

Bei Checkbox verstehe ich grade sebst nicht was da abgeht...

**Comment by mathe42** [comment]
evtl. habe ich für die Checkbox einen Fix / einen Weg wie Checkbox anders eingebunden wird... PR kann meinetwegen gemergt werden issue aber noch nicht schließen...
