### ISSUE TITLE
TypeError beim erneuten Routen zu einem Lesezeichen

### ISSUE THREAD

**Issue by tobikrs** [ecnordbund/ec-verwaltungs-app#108]
Wenn man durch die Lesezeichen funktion zu einem Lesezeichen navigiert und dann ein anderes auswählen möchte. Passiert nichts.

Folgende Fehler-Meldung wird in der Console ausgegeben:

```
Uncaught (in promise) TypeError: v.data is not a function
    at Object.query.then (details.vue?cac2:334)
    at <anonymous>
```

**Comment by mathe42** [comment]
Könnte mit dem Router-Hock zusammenhängen...

**Comment by mathe42** [comment]
Es fehlt ein ;

**Comment by mathe42** [comment]
#111  fixt das...
