### ISSUE TITLE
Fix 5 Duplication issues in src\graphql\index.ts

### ISSUE THREAD

**Issue by mathe42** [ecnordbund/ec-verwaltungs-app#143]
[CodeFactor](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/overview/master) found multiple issues last seen at 6c4567c4d3c10b2e669c26b9c50651dd366feca1:

#### Duplicate Code
[src\graphql\index.ts:289-299
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L289)[src\graphql\index.ts:482-492
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L482)[src\graphql\index.ts:496-509
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L496)[src\graphql\index.ts:264-277
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L264)[src\graphql\index.ts:435-450
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L435)[src\graphql\index.ts:800-815
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L800)[src\graphql\index.ts:452-471
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L452)[src\graphql\index.ts:779-798
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L779)[src\graphql\index.ts:81-94
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L81)[src\graphql\index.ts:12-25
](https://www.codefactor.io/repository/github/ecnordbund/ec-verwaltungs-app/source/master/src/graphql/index.ts#L12)

Da sollte man mal drüber sehen

**Comment by tobikrs** [comment]
Da das die gql-Befehle sind ist das doch gar nicht zu vermeiden, oder?

**Comment by mathe42** [comment]
Ich habe mir das nicht genauer angesehen… Das sah danach aus als ob es Querrys doppelt gab und das würde sich vermeiden lassen…

**Comment by mathe42** [comment]
Hab ich mir grade angesehen ist alles OK...
