### ISSUE TITLE
[Build] Spinner + Logos

### ISSUE THREAD

**Issue by mathe42** [ecnordbund/ec-verwaltungs-app#22]
Tobi,
Kannst du bitte aus dem EC Logo einen Lade-Spinner machen? (als .gif)

Brauche ich für den Build-Prozess

**Comment by mathe42** [comment]
+ Ich brauche noch für den Installer + Browserwindow ein Icon als Logo

(als .ico, und .png) für MacOS evtl. weiteres Format...

**Comment by tobikrs** [comment]
Logo für unsere Application?

![ec-logo-128.png](https://user-images.githubusercontent.com/39905423/41864925-cf69fedc-78ab-11e8-9bf4-87a220c4d8f7.png)

**Comment by mathe42** [comment]
Binde ich gleich Mal ein.

Das gif hat sich erledigt

**Comment by mathe42** [comment]
@tobikrs  kannst du das Bild auch noch als 256x256 mir schicken...?

**Comment by tobikrs** [comment]
s. E-Mail
