### ISSUE TITLE
[Funktion] UX

### ISSUE THREAD

**Issue by mathe42** [ecnordbund/ec-verwaltungs-app#60]
Hier einfach mal listen was wir an UX verbessern müssen.

- [x] focus on username field on `window.ready` (at login screen)
- [x] wenn window groß genug, menü immer offen (->nicht nötig denke ich da durch persistent drawer ähnliches erreicht wurde dann dem User mehr freiraum lassen)
- [x] verbesserung der Beschriftungen & vereinheitlichen von Sprachen von UI-Elementen

**Comment by tobikrs** [comment]
`focus on username` done with 017b3b30dbbf44ee68ac5a1549c94823bcf5c2a7

**Comment by tobikrs** [comment]
- [x] `persistent drawer` done with dd0a20b33c363986724ad71dd2dea88db1e9f3c3

**Comment by mathe42** [comment]
Was meinst du mit dem 3. Punkt?

**Comment by tobikrs** [comment]
Naja, dass die Begriffe so gewählt sind, dass Benutzer anhand derer die UI optimal bedienen kann.

Ich glaube wir sind schon gut dabei aber zum Release 1.0 sollten wir die UI nochmal auf diese Art von Optimierung durchsuchen.

**Comment by tobikrs** [comment]
Ist es möglich den RouteBack-Button nur anzuzeigen solange der Breakpoint für den drawer noch nicht erreicht ist?

Ich bin vorhin nicht so schnell eingestiegen, wie du den implementiert hast und wie man das Verhalten implementieren könnte...

**Comment by mathe42** [comment]
Verstehe ich nicht...

**Comment by tobikrs** [comment]
Ok: Das drawer menu ist ja jetzt immer ausgefahren. Allerdings nicht wenn die Fensterbreite unter `1264px` ist. Dann ist es wie gehabt eingeklappt.

Mein Verbesserungsvorschlag ist den roten Zurück-Button oben links auf den Seiten mit den Listen (Personen, AKs, Verteiler, usw.) aber auch Admin und so nicht per default nicht mehr anzuzeigen, ausßer wenn der Drawer nicht mehr standardmäsig ausgeklappt ist und der Zurück-Button eine sinnvolle Navigationsmöglichkeit bietet. Mit `Breakpoint` sind die `1264px` gemeint bei dem sich dieses Verhalten ändern soll.

Ich bräuchte evtl. deine Hilfe wenn es für das Feature nötig ist die Implementierung des _Component_ für den Zurück-Button zu verändern, in dem man neue `props` für den _Component_ definieren muss.

**Comment by mathe42** [comment]
Aber der Zurück Button liefert mehr als nur die Möglichkeiten des Drawers:

z.B. ich wähle Person X aus dann schaue ich mir die Anmeldungen an und klicke auf eine -> Neuer Route zur Anmelde Details page...

**Comment by mathe42** [comment]
Da macht sich ein Zurück Button sehr gut.

**Comment by mathe42** [comment]
Auch kann ich den Drawer IMMER zu machen auch bei über 1264px

**Comment by mathe42** [comment]
Die Home-Seite ist übrigens erstmal so fertig es muss nur #74 gemacht werden...

Settings etc. für die Widgets können wir Später nachliefern...

**Comment by tobikrs** [comment]
Guter Einwand... aber ich meinte auch nur diese ersten Seiten wo er wirklich überflüssig (oder sogar verwirrent) ist...

Habe es geschafft zu implementieren (s. adf248c51c1678c57e9ba328a662ef730365cb16)

**Comment by tobikrs** [comment]
Evtl. sollten wir als zusätzliche Bedingung nehmen, dass er nur nicht angezeigt werden soll wenn die `Route` eine bestimmt länge hat (weil es dann über das Menu simpler zu bedienen wäre)

Verstehste wie ich das mein?
Wenn wir das Implementiert haben können wir es auf `dev` packen.

**Comment by mathe42** [comment]
Aber ist es dann nicht sinnvoller den Button immer anzuzeigen?

**Comment by mathe42** [comment]
Alternativ können wir auch gerne eine Tastenkombination einführen die immer $router.back() ausführt z.B. strg + B

**Comment by mathe42** [comment]
Ich bin eh aktuell am überlegen wie man cool STRG + C/V/S/P einbauen kann
