### ISSUE TITLE
[Build-CI] Build in CI-Server aktivieren

### ISSUE THREAD

**Issue by mathe42** [ecnordbund/ec-verwaltungs-app#9]
Durch den Rewrite aller Components und einen anderen Compile-Workflow muss die CI neu eingerichtet und konfiguriert werden. Dafür ist es notwendig vorher noch die Forge-Config anzupassen.

**Comment by mathe42** [comment]
Aktuell TypeError-Bug... Daher geht noch nicht automatisch...

**Comment by ecnordbund** [comment]
Für Linux + MacOS fast fertig.... (Der TypeError verhindert Windows)

**Comment by ecnordbund** [comment]
Type Error wird beim nächsten Apollo-Vue Release wohl gefixt sein...

**Comment by mathe42** [comment]
Grund des Fehlers: Typescript 2.9

**Comment by ecnordbund** [comment]
To-Do: wenn pr nicht publizieren sondern nur make...

**Comment by ecnordbund** [comment]
To-Do: badges

**Comment by ecnordbund** [comment]
Neuer Apollo-Vue Release. Kann also wieder zurück gemacht werden
