### ISSUE TITLE
(Funktion) Infotext

### ISSUE THREAD

**Issue by mathe42** [ecnordbund/ec-verwaltungs-app#90]
Beim ersten start der App und alle 12 Monate und wenn sich der Text ändert, ein Popup kommen wo man einer Datenschutzerklärung und hinweisen zum Umgang mit den Daten zustimmen muss.

Text sollte anpassbar sein ohne die App neu zu releasen...

**Comment by tobikrs** [comment]
## thoughts on the issue

1.  Einblendung der DSE müsste right nach dem Login erfolgen.
2. Darüber können wir wissen ob Nutzer im vergangenem Jahr oder je schon zugestimmt hat.
3. Text sollte von Server durch ein API-Request geladen werden (dadurch auch jederzeit änderbar)
4. Zudem sollten wir für jede Text-Änderung einen neuen Datensatz anlegen um zu tracken welcher Nutzer welcher DSE-Version zugestimmt hat und ggf. die neue Version zu zeigen.
5. Text sollte eine simple Syntax (Markdown, oder abgespeckte Markdown-Variante) haben um z.B. Zeilenumbrüche, fett, rekursiv, Überschriften (Layer 1-3) zu parsen.
6. Am Besten wäre wenn eine Usergruppe die DSE und Nutzungshinweise in der App bearbeiten könnte.
7. DSE und Nutzungshinweise sollten jederzeit in der App einsehbar sein

**Comment by tobikrs** [comment]
## Substeps

- [ ] Datenbank Tabelle + Felder `DSE_ID`, `text`, `gültigAb` erstellen @mathe42 
- [ ] API-Requests: @mathe42 
  - `setDSE(text, güligAbDatum)`
  - `getCurrentDSE_ID()`
  - `getDSEWith(DSE_ID)`
  - `updateGültigkeit(DSE_ID, newGültigAbDatum)`
  - (`getHistory()`)
- [ ] Datenbank: User-Tabelle um Feld `acceptedDSEs: Array<{DSE_ID, timestamp}>` erweitern. @mathe42 
- [ ] User API-Requests: @mathe42 
  - `acceptsDSE(DSE_ID, UserID, timestamp)`
- [ ] nach login(), vor verlassen Login-Screen: API-Request (`getCurrentDSE_ID()`)
  - wenn User `currentDSE_ID` schon zugestimmt hat --> Login-Screen verlassen.
  - sonst API-Request `getDSEWith(currentDSE_ID)`, dann DSE-Dialog öffnen
- [ ] DSE-Dialog:
  - nicht wegklickbar
  - unten Buttons: `beenden` und `weiter` (deaktiviert solange nicht zugestimmt)
  - statischer Dialog-Titel
  - Dialog hat max-height, Text muss bei Überlänge scrollbar sein
  - statisch am Ende des Textes Acceptance-Checkbox
  - weiter-Button: `@click` -> API-Request `accetsDSE(...)` 
- [ ] DSE-Editor:
  - nur sichtbar für bestimmte Usergruppe
  - erstmal reicht einfaches Textfeld wo DSE der Text inkl. Syntax verfasst werden kann
  - Datepicker, ab wann gültig
  - Speichern: `@click`-> API-Request `setDSE(...)`

**Comment by mathe42** [comment]
Grob korrekt...

**Comment by mathe42** [comment]
Würde die API vereinfachter nutzen...

**Comment by mathe42** [comment]
Ich würde vorschlagen im ersten schritt die DSE erstmal nicht editierbar zu machen Thomas sollte nicht unbedingt markdown lernen müssen

**Comment by mathe42** [comment]
Die zustimmungen etc ansehen brauchen wir nicht.

Wenn wir aufgevordert werden die behlerungen der MA darzulegen können wir das aus der DB kopieren... Das ist dann weniger aufwand als das jetzt zu implementieren

**Comment by mathe42** [comment]
Auch editieren vorhandener Texte ist nicht notwendig. Dann muss ein neuer Angelegt werden...

**Comment by mathe42** [comment]
API angepasst muss aber noch gepullt werden...

**Comment by mathe42** [comment]
@tobikrs Ist quasi fertig bitte mal in den mutations branch schauen....

Editieren fehlt noch ist aber in arbeit...

**Comment by mathe42** [comment]
Ist fertig
